services:
  web_ap:
    build: .
    command: python app.py
    ports:
      - 5000:5000
    environment:
      - RABBITMQ_HOST=rabbit_host

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbit_host

  celery_worker:
    build: .
    command: celery -A celery_tasks worker --loglevel=INFO --pool=solo
    environment:
      - RABBITMQ_HOST=rabbit_host