"""signed datetime column for contract

Revision ID: 1482392865b3
Revises: d39d4741e0b3
Create Date: 2025-02-26 14:50:03.105842
3
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1482392865b3'
down_revision: Union[str, None] = 'd39d4741e0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('signed_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'signed_datetime')
    # ### end Alembic commands ###
