"""favorites

Revision ID: 550bd1b74db9
Revises: 6ada816df0dc
Create Date: 2025-02-26 16:08:04.272083
3
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550bd1b74db9'
down_revision: Union[str, None] = '6ada816df0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'timestamp')
    # ### end Alembic commands ###
